In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [21]:
t={
    0:'setosa',
    1:'versicolor',
    2:'virginica'
}

In [23]:
iris=load_iris()
df=pd.DataFrame(iris.data)

In [26]:
df['target_names']=iris.target

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
df.head()

     0    1    2    3  target_names
0  5.1  3.5  1.4  0.2             0
1  4.9  3.0  1.4  0.2             0
2  4.7  3.2  1.3  0.2             0
3  4.6  3.1  1.5  0.2             0
4  5.0  3.6  1.4  0.2             0

In [28]:
df['target_names']=df['target_names'].map(t)

In [29]:
df.head()

     0    1    2    3 target_names
0  5.1  3.5  1.4  0.2       setosa
1  4.9  3.0  1.4  0.2       setosa
2  4.7  3.2  1.3  0.2       setosa
3  4.6  3.1  1.5  0.2       setosa
4  5.0  3.6  1.4  0.2       setosa

In [13]:
df.shape

(150, 4)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [17]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')