# Linear Regression

In [72]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [46]:
df=pd.read_csv('../data/kc_house_data.csv')

In [47]:
df.head()

           id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [48]:
df.shape

(21613, 21)

In [50]:
df.drop('date',axis=1,inplace=True)
#df.drop('id',axis=1,inplace=True)

In [51]:
df['waterfront'].value_counts()
df['view'].value_counts()

view
0    19489
2      963
3      510
1      332
4      319
Name: count, dtype: int64

In [52]:
df['age']=df['yr_built'].max()-df['yr_built']

In [53]:
df.drop('yr_built',axis=1,inplace=True)

In [35]:
x=df['yr_renovated'].values != 0
xd=pd.DataFrame(x)
xd.value_counts()

0
False    20699
True       914
Name: count, dtype: int64

In [54]:
df.drop('yr_renovated',axis=1,inplace=True)

In [55]:
df.head()

      price  bedrooms  bathrooms  ...  sqft_living15  sqft_lot15  age
0  221900.0         3       1.00  ...           1340        5650   60
1  538000.0         3       2.25  ...           1690        7639   64
2  180000.0         2       1.00  ...           2720        8062   82
3  604000.0         4       3.00  ...           1360        5000   50
4  510000.0         3       2.00  ...           1800        7503   28

[5 rows x 18 columns]

In [15]:
df['yr_built'].min()

1900

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21613 non-null  float64
 1   bedrooms       21613 non-null  int64
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64
 4   sqft_lot       21613 non-null  int64
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64
 7   view           21613 non-null  int64
 8   condition      21613 non-null  int64
 9   grade          21613 non-null  int64
 10  sqft_above     21613 non-null  int64
 11  sqft_basement  21613 non-null  int64
 12  zipcode        21613 non-null  int64
 13  lat            21613 non-null  float64
 14  long           21613 non-null  float64
 15  sqft_living15  21613 non-null  int64
 16  sqft_lot15     21613 non-null  int64
 17  age            21613 non-null  int64
dtypes: float64(5), int64(13)
memory usage: 3.0 MB

In [42]:
x=df.drop('price',axis=1,inplace=False)
y=df['price']

In [43]:
y.head()

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [56]:
df.describe()

              price      bedrooms  ...     sqft_lot15           age
count  2.161300e+04  21613.000000  ...   21613.000000  21613.000000
mean   5.400881e+05      3.370842  ...   12768.455652     43.994864
std    3.671272e+05      0.930062  ...   27304.179631     29.373411
min    7.500000e+04      0.000000  ...     651.000000      0.000000
25%    3.219500e+05      3.000000  ...    5100.000000     18.000000
50%    4.500000e+05      3.000000  ...    7620.000000     40.000000
75%    6.450000e+05      4.000000  ...   10083.000000     64.000000
max    7.700000e+06     33.000000  ...  871200.000000    115.000000

[8 rows x 18 columns]

In [41]:
x.head()

   bedrooms  bathrooms  sqft_living  ...  sqft_living15  sqft_lot15  age
0         3       1.00         1180  ...           1340        5650   82
1         3       2.25         2570  ...           1690        7639   82
2         2       1.00          770  ...           2720        8062   82
3         4       3.00         1960  ...           1360        5000   82
4         3       2.00         1680  ...           1800        7503   82

[5 rows x 17 columns]

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [61]:
df.shape

(21613, 18)

In [60]:
x_train.shape

(17290, 17)

In [64]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [69]:
y_pr=pd.DataFrame(model.predict(x_test))

In [70]:
type(y_pr)

pandas.core.frame.DataFrame